apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080 # Dit is een voorbeeld, je kunt een ander poortnummer kiezen tussen 30000 en 32767
  type: NodePort
